version: '3'

services:
  #mongo database
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo_container'
    ports:
      - '27017:27017'
  # Django web
  djweb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'django_container'
    ports:
      - "8000:8000"
    links:
      - mongo  
  


