# Generated by Django 2.2.16 on 2022-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_demousers_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
